config/routes.rb
Rails.application.routes.draw do
  resources :manifestation_relationship_types

  resources :catalogs

  resources :languages

  resources :controlled_access_points

  resources :identifiers

  resources :names

  resources :corporate_bodies

  resources :families

  resources :expression_relationship_types

  resources :expression_relationships

  resources :work_relationship_types

  resources :work_relationships

  resources :patrons

  resources :subjects

  resources :creates

  resources :realizes

  resources :produces

  resources :content_types

  resources :carrier_types

  resources :reifies

  resources :embodies

  resources :works

  resources :expressions

  resources :exemplifies

  resources :items

  resources :people

  resources :manifestations

  root :to => 'works#index'

  match '/bib_id/:bib_id' => 'manifestations#show'
end

app/models/name.rb
class Name < ActiveRecord::Base
  attr_accessible :dates_of_usage, :language_id, :name_string, :scope_of_usage, :script, :transliteration_scheme, :type_of_name
  belongs_to :language
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  # GET /names
  # GET /names.json
  def index
    @names = Name.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @names }
    end
  end

  # GET /names/1
  # GET /names/1.json
  def show
    @name = Name.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/new
  # GET /names/new.json
  def new
    @name = Name.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/1/edit
  def edit
    @name = Name.find(params[:id])
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(params[:name])

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render json: @name, status: :created, location: @name }
      else
        format.html { render action: "new" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /names/1
  # PUT /names/1.json
  def update
    @name = Name.find(params[:id])

    respond_to do |format|
      if @name.update_attributes(params[:name])
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name = Name.find(params[:id])
    @name.destroy

    respond_to do |format|
      format.html { redirect_to names_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_of_name %><br />
    <%= f.text_field :type_of_name %>
  </div>
  <div class="field">
    <%= f.label :name_string %><br />
    <%= f.text_field :name_string %>
  </div>
  <div class="field">
    <%= f.label :scope_of_usage %><br />
    <%= f.text_area :scope_of_usage %>
  </div>
  <div class="field">
    <%= f.label :dates_of_usage %><br />
    <%= f.text_area :dates_of_usage %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.number_field :language_id %>
  </div>
  <div class="field">
    <%= f.label :script %><br />
    <%= f.text_field :script %>
  </div>
  <div class="field">
    <%= f.label :transliteration_scheme %><br />
    <%= f.text_field :transliteration_scheme %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<div id="content_detail" class="ui-corner-all">
  <h1 class="title">Listing names</h1>
  <div id="content_list">

<table>
  <tr>
    <th>Type of name</th>
    <th>Name string</th>
    <th>Scope of usage</th>
    <th>Dates of usage</th>
    <th>Language</th>
    <th>Script</th>
    <th>Transliteration scheme</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= name.type_of_name %></td>
    <td><%= name.name_string %></td>
    <td><%= name.scope_of_usage %></td>
    <td><%= name.dates_of_usage %></td>
    <td><%= name.language_id %></td>
    <td><%= name.script %></td>
    <td><%= name.transliteration_scheme %></td>
    <td><%= link_to 'Show', name %></td>
    <td><%= link_to 'Edit', edit_name_path(name) %></td>
    <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= paginate(@names) %>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to 'New Name', new_name_path %></li>
  </ul>
</div>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render 'form' %>

<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type of name:</b>
  <%= @name.type_of_name %>
</p>

<p>
  <b>Name string:</b>
  <%= @name.name_string %>
</p>

<p>
  <b>Scope of usage:</b>
  <%= @name.scope_of_usage %>
</p>

<p>
  <b>Dates of usage:</b>
  <%= @name.dates_of_usage %>
</p>

<p>
  <b>Language:</b>
  <%= @name.language_id %>
</p>

<p>
  <b>Script:</b>
  <%= @name.script %>
</p>

<p>
  <b>Transliteration scheme:</b>
  <%= @name.transliteration_scheme %>
</p>


<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>