config/routes.rb
Rails.application.routes.draw do
  resources :manifestation_relationship_types

  resources :catalogs

  resources :languages

  resources :controlled_access_points

  resources :identifiers

  resources :names

  resources :corporate_bodies

  resources :families

  resources :expression_relationship_types

  resources :expression_relationships

  resources :work_relationship_types

  resources :work_relationships

  resources :patrons

  resources :subjects

  resources :creates

  resources :realizes

  resources :produces

  resources :content_types

  resources :carrier_types

  resources :reifies

  resources :embodies

  resources :works

  resources :expressions

  resources :exemplifies

  resources :items

  resources :people

  resources :manifestations

  root :to => 'works#index'

  match '/bib_id/:bib_id' => 'manifestations#show'
end

app/models/work_relationship.rb
class WorkRelationship < ActiveRecord::Base
  attr_accessible :child_id, :parent_id, :work_relationship_type_id

  belongs_to :parent, :foreign_key => 'parent_id', :class_name => 'Work'
  belongs_to :child, :foreign_key => 'child_id', :class_name => 'Work'
  belongs_to :work_relationship_type
  validate :check_parent
  validates :parent_id, :presence => true
  validates :child_id, :uniqueness => {:scope => :parent_id}, :presence => true

  after_save :create_index, :generate_graph

  def check_parent
    errors.add(:parent) if parent_id == child_id
  end

  def create_index
    parent.index
    child.index
    Sunspot.commit
  end

  def generate_graph
    parent.generate_graph
    child.generate_graph
  end
end

app/models/work_relationship_type.rb
class WorkRelationshipType < ActiveRecord::Base
  attr_accessible :name, :position, :definition, :url
  acts_as_list
end

app/controllers/work_relationships_controller.rb
class WorkRelationshipsController < ApplicationController
  before_filter :prepare_options, :only => [:new, :edit]

  # GET /work_relationships
  # GET /work_relationships.json
  def index
    @work_relationships = WorkRelationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_relationships }
    end
  end

  # GET /work_relationships/1
  # GET /work_relationships/1.json
  def show
    @work_relationship = WorkRelationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_relationship }
    end
  end

  # GET /work_relationships/new
  # GET /work_relationships/new.json
  def new
    @work_relationship = WorkRelationship.new
    @work_relationship.parent = Work.find(params[:parent_id])
    @work_relationship.child = Work.find(params[:child_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_relationship }
    end
  end

  # GET /work_relationships/1/edit
  def edit
    @work_relationship = WorkRelationship.find(params[:id])
  end

  # POST /work_relationships
  # POST /work_relationships.json
  def create
    @work_relationship = WorkRelationship.new(params[:work_relationship])

    respond_to do |format|
      if @work_relationship.save
        format.html { redirect_to @work_relationship, notice: 'Work relationship was successfully created.' }
        format.json { render json: @work_relationship, status: :created, location: @work_relationship }
      else
        prepare_options
        format.html { render action: "new" }
        format.json { render json: @work_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_relationships/1
  # PUT /work_relationships/1.json
  def update
    @work_relationship = WorkRelationship.find(params[:id])

    respond_to do |format|
      if @work_relationship.update_attributes(params[:work_relationship])
        format.html { redirect_to @work_relationship, notice: 'Work relationship was successfully updated.' }
        format.json { head :no_content }
      else
        prepare_options
        format.html { render action: "edit" }
        format.json { render json: @work_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_relationships/1
  # DELETE /work_relationships/1.json
  def destroy
    @work_relationship = WorkRelationship.find(params[:id])
    @work_relationship.destroy

    respond_to do |format|
      format.html { redirect_to work_relationships_url }
      format.json { head :no_content }
    end
  end

  private
  def prepare_options
    @relationship_types = WorkRelationshipType.all
  end
end

app/helpers/work_relationships_helper.rb
module WorkRelationshipsHelper
end

app/views/work_relationships/_form.html.erb
<%= form_for(@work_relationship) do |f| %>
  <% if @work_relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_relationship.errors.count, "error") %> prohibited this work_relationship from being saved:</h2>

      <ul>
      <% @work_relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br />
    <%= link_to @work_relationship.parent.original_title, @work_relationship.parent %>
    <%= f.hidden_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :child_id %><br />
    <%= link_to @work_relationship.child.original_title, @work_relationship.child %>
    <%= f.hidden_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :work_relationship_type_id %><br />
    <%= f.select(:work_relationship_type_id, @relationship_types.map{|w| [w.name, w.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_relationships/edit.html.erb
<h1>Editing work_relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_relationship %> |
<%= link_to 'Back', work_relationships_path %>

app/views/work_relationships/index.html.erb
<h1>Listing work_relationships</h1>

<table>
  <tr>
    <th>Parent</th>
    <th>Child</th>
    <th>Work relationship type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @work_relationships.each do |work_relationship| %>
  <tr>
    <td><%= work_relationship.parent_id %></td>
    <td><%= work_relationship.child_id %></td>
    <td><%= work_relationship.work_relationship_type_id %></td>
    <td><%= link_to 'Show', work_relationship %></td>
    <td><%= link_to 'Edit', edit_work_relationship_path(work_relationship) %></td>
    <td><%= link_to 'Destroy', work_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Work relationship', new_work_relationship_path %>

app/views/work_relationships/new.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title">New work_relationship</h1>
<div id="content_list">

<%= render 'form' %>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to 'Back', work_relationships_path %></li>
  </ul>
</div>

app/views/work_relationships/show.html.erb
<div id="content_detail" class="ui-corner-all">
<div id="content_list">
<p id="notice"><%= notice %></p>

<p>
  <b>Parent:</b>
  <%= link_to @work_relationship.parent.original_title, @work_relationship.parent %>
</p>

<p>
  <b>Child:</b>
  <%= link_to @work_relationship.child.original_title, @work_relationship.child %>
</p>

<p>
  <b>Work relationship type:</b>
  <%= @work_relationship.work_relationship_type_id %>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.edit'), edit_work_relationship_path(@work_relationship) %></li>
    <li><%= link_to t('page.back'), work_relationships_path %></li>
  </ul>
</div>