config/routes.rb
Rails.application.routes.draw do
  resources :manifestation_relationship_types

  resources :catalogs

  resources :languages

  resources :controlled_access_points

  resources :identifiers

  resources :names

  resources :corporate_bodies

  resources :families

  resources :expression_relationship_types

  resources :expression_relationships

  resources :work_relationship_types

  resources :work_relationships

  resources :patrons

  resources :subjects

  resources :creates

  resources :realizes

  resources :produces

  resources :content_types

  resources :carrier_types

  resources :reifies

  resources :embodies

  resources :works

  resources :expressions

  resources :exemplifies

  resources :items

  resources :people

  resources :manifestations

  root :to => 'works#index'

  match '/bib_id/:bib_id' => 'manifestations#show'
end

app/models/corporate_body.rb
class CorporateBody < ActiveRecord::Base
  attr_accessible :address, :date_associated, :field_of_activity, :history, :language_id, :other_information, :place_associated
end

app/controllers/corporate_bodies_controller.rb
class CorporateBodiesController < ApplicationController
  # GET /corporate_bodies
  # GET /corporate_bodies.json
  def index
    @corporate_bodies = CorporateBody.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corporate_bodies }
    end
  end

  # GET /corporate_bodies/1
  # GET /corporate_bodies/1.json
  def show
    @corporate_body = CorporateBody.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @corporate_body }
    end
  end

  # GET /corporate_bodies/new
  # GET /corporate_bodies/new.json
  def new
    @corporate_body = CorporateBody.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @corporate_body }
    end
  end

  # GET /corporate_bodies/1/edit
  def edit
    @corporate_body = CorporateBody.find(params[:id])
  end

  # POST /corporate_bodies
  # POST /corporate_bodies.json
  def create
    @corporate_body = CorporateBody.new(params[:corporate_body])

    respond_to do |format|
      if @corporate_body.save
        format.html { redirect_to @corporate_body, notice: 'Corporate body was successfully created.' }
        format.json { render json: @corporate_body, status: :created, location: @corporate_body }
      else
        format.html { render action: "new" }
        format.json { render json: @corporate_body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corporate_bodies/1
  # PUT /corporate_bodies/1.json
  def update
    @corporate_body = CorporateBody.find(params[:id])

    respond_to do |format|
      if @corporate_body.update_attributes(params[:corporate_body])
        format.html { redirect_to @corporate_body, notice: 'Corporate body was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @corporate_body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporate_bodies/1
  # DELETE /corporate_bodies/1.json
  def destroy
    @corporate_body = CorporateBody.find(params[:id])
    @corporate_body.destroy

    respond_to do |format|
      format.html { redirect_to corporate_bodies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/corporate_bodies_helper.rb
module CorporateBodiesHelper
end

app/views/corporate_bodies/_form.html.erb
<%= form_for(@corporate_body) do |f| %>
  <% if @corporate_body.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corporate_body.errors.count, "error") %> prohibited this corporate_body from being saved:</h2>

      <ul>
      <% @corporate_body.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_associated %><br />
    <%= f.text_area :place_associated %>
  </div>
  <div class="field">
    <%= f.label :date_associated %><br />
    <%= f.text_area :date_associated %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.number_field :language_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :field_of_activity %><br />
    <%= f.text_area :field_of_activity %>
  </div>
  <div class="field">
    <%= f.label :history %><br />
    <%= f.text_area :history %>
  </div>
  <div class="field">
    <%= f.label :other_information %><br />
    <%= f.text_area :other_information %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/corporate_bodies/edit.html.erb
<h1>Editing corporate_body</h1>

<%= render 'form' %>

<%= link_to 'Show', @corporate_body %> |
<%= link_to 'Back', corporate_bodies_path %>

app/views/corporate_bodies/index.html.erb
<h1>Listing corporate_bodies</h1>

<table>
  <tr>
    <th>Place associated</th>
    <th>Date associated</th>
    <th>Language</th>
    <th>Address</th>
    <th>Field of activity</th>
    <th>History</th>
    <th>Other information</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @corporate_bodies.each do |corporate_body| %>
  <tr>
    <td><%= corporate_body.place_associated %></td>
    <td><%= corporate_body.date_associated %></td>
    <td><%= corporate_body.language_id %></td>
    <td><%= corporate_body.address %></td>
    <td><%= corporate_body.field_of_activity %></td>
    <td><%= corporate_body.history %></td>
    <td><%= corporate_body.other_information %></td>
    <td><%= link_to 'Show', corporate_body %></td>
    <td><%= link_to 'Edit', edit_corporate_body_path(corporate_body) %></td>
    <td><%= link_to 'Destroy', corporate_body, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Corporate body', new_corporate_body_path %>

app/views/corporate_bodies/new.html.erb
<h1>New corporate_body</h1>

<%= render 'form' %>

<%= link_to 'Back', corporate_bodies_path %>

app/views/corporate_bodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place associated:</b>
  <%= @corporate_body.place_associated %>
</p>

<p>
  <b>Date associated:</b>
  <%= @corporate_body.date_associated %>
</p>

<p>
  <b>Language:</b>
  <%= @corporate_body.language_id %>
</p>

<p>
  <b>Address:</b>
  <%= @corporate_body.address %>
</p>

<p>
  <b>Field of activity:</b>
  <%= @corporate_body.field_of_activity %>
</p>

<p>
  <b>History:</b>
  <%= @corporate_body.history %>
</p>

<p>
  <b>Other information:</b>
  <%= @corporate_body.other_information %>
</p>


<%= link_to 'Edit', edit_corporate_body_path(@corporate_body) %> |
<%= link_to 'Back', corporate_bodies_path %>