config/routes.rb
Rails.application.routes.draw do
  resources :manifestation_relationship_types

  resources :catalogs

  resources :languages

  resources :controlled_access_points

  resources :identifiers

  resources :names

  resources :corporate_bodies

  resources :families

  resources :expression_relationship_types

  resources :expression_relationships

  resources :work_relationship_types

  resources :work_relationships

  resources :patrons

  resources :subjects

  resources :creates

  resources :realizes

  resources :produces

  resources :content_types

  resources :carrier_types

  resources :reifies

  resources :embodies

  resources :works

  resources :expressions

  resources :exemplifies

  resources :items

  resources :people

  resources :manifestations

  root :to => 'works#index'

  match '/bib_id/:bib_id' => 'manifestations#show'
end

app/models/produce.rb
class Produce < ActiveRecord::Base
  attr_accessible :manifestation_id, :person_id
  belongs_to :manifestation
  belongs_to :person
end

app/controllers/produces_controller.rb
class ProducesController < ApplicationController
  # GET /produces
  # GET /produces.json
  def index
    @produces = Produce.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produces }
    end
  end

  # GET /produces/1
  # GET /produces/1.json
  def show
    @produce = Produce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produce }
    end
  end

  # GET /produces/new
  # GET /produces/new.json
  def new
    @produce = Produce.new
    @person = Person.find(params[:person_id]) if params[:person_id]
    @manifestation = Manifestation.find(params[:manifestation_id]) if params[:manifestation_id]
    @produce.person = @person
    @produce.manifestation = @manifestation

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produce }
    end
  end

  # GET /produces/1/edit
  def edit
    @produce = Produce.find(params[:id])
  end

  # POST /produces
  # POST /produces.json
  def create
    @produce = Produce.new(params[:produce])

    respond_to do |format|
      if @produce.save
        format.html { redirect_to @produce, notice: 'Produce was successfully created.' }
        format.json { render json: @produce, status: :created, location: @produce }
      else
        format.html { render action: "new" }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produces/1
  # PUT /produces/1.json
  def update
    @produce = Produce.find(params[:id])

    respond_to do |format|
      if @produce.update_attributes(params[:produce])
        format.html { redirect_to @produce, notice: 'Produce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produces/1
  # DELETE /produces/1.json
  def destroy
    @produce = Produce.find(params[:id])
    @produce.destroy

    respond_to do |format|
      format.html { redirect_to produces_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produces_helper.rb
module ProducesHelper
end

app/views/produces/_form.html.erb
<%= form_for(@produce) do |f| %>
  <% if @produce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produce.errors.count, "error") %> prohibited this produce from being saved:</h2>

      <ul>
      <% @produce.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manifestation %><br />
    <%= link_to @produce.manifestation.title_proper, @produce.manifestation %>
    <br />
    <%= f.hidden_field :manifestation_id %>
  </div>
  <div class="field">
    <%= f.label :person %><br />
    <%= link_to @produce.person.full_name, @produce.person %>
    <br />
    <%= f.hidden_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produces/edit.html.erb
<h1 class="title">Editing produce</h1>

<%= render 'form' %>

<%= link_to t('enju.show'), @produce %> |
<%= link_to t('enju.back'), produces_path %>

app/views/produces/index.html.erb
<h1 class="title">Listing produces</h1>

<table class="index">
  <tr class="line<%= cycle("0", "1") -%>">
    <th>Manifestation</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @produces.each do |produce| %>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= produce.manifestation %></td>
    <td><%= produce.person %></td>
    <td><%= link_to t('enju.show'), produce %></td>
    <td><%= link_to t('enju.edit'), edit_produce_path(produce) %></td>
    <td><%= link_to t('enju.destroy'), produce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Produce', new_produce_path %>

app/views/produces/new.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title">New produce</h1>
<div id="content_list">

<%= render 'form' %>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('enju.back'), produces_path %></li>
  </ul>
</div>

app/views/produces/show.html.erb
<div id="content_detail" class="ui-corner-all">
<div id="content_list">
<p id="notice"><%= notice %></p>

<p>
  <b>Manifestation:</b>
  <%= link_to @produce.manifestation.title_proper, @produce.manifestation %>
</p>

<p>
  <b>Person:</b>
  <%= link_to @produce.person.full_name, @produce.person %>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('enju.edit'), edit_produce_path(@produce) %></li>
    <li><%= link_to t('enju.back'), produces_path %></li>
  </ul>
</div>